### ISSUE TITLE
Buttons in the nav bar are invalid

### ISSUE THREAD

**Issue by LuckyHookin** [marktext/website#17]
![2](https://user-images.githubusercontent.com/45350455/68850752-a0173200-070f-11ea-9473-c66c9f914f3c.gif)

**Comment by LuckyHookin** [comment]
Windows 10
Google Chrome version: 78.0.3904.97

**Comment by LuckyHookin** [comment]
# src/utils/scrollTo.js:
## add:
```
console.table({ lastpos: lastpos,
              scrollTop: element.scrollTop,
              animating: animating });
```
![scrollTo.js](https://user-images.githubusercontent.com/45350455/68852799-9db6d700-0713-11ea-974b-3583fc3c4f51.png)
## output:
![image](https://user-images.githubusercontent.com/45350455/68852904-c939c180-0713-11ea-9012-bff359dfd9ed.png)

**Comment by LuckyHookin** [comment]
Because `element.scrollTop` returns a decimal, not an integer. The scrolling animation ends early.??

**Comment by Jocs** [comment]
I'm sorry I just replied now, because I'm really busy recently, there should be no problem with PR, I merged, thank you

**Comment by LuckyHookin** [comment]
"scrollTop getter/setter value is affected by zoom-factor":
[chromium bugs Page](https://bugs.chromium.org/p/chromium/issues/detail?id=772393&q=scrollTop&can=2)
