### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by OckhamOdyssey** [marktext/website#66]
Unable to see the webpage on any browser. Error given `ERR_CONNECTION_CLOSED`.

**Comment by aleung** [comment]
The domain name is for sale now.

**Comment by KaKi87** [comment]
Why not renew it ?
By the way, the README still points to it.

**Comment by Jocs** [comment]
Please visit [www.marktext.cc](http://www.marktext.cc/)

**Comment by KaKi87** [comment]
Why changing the domain extension ?

**Comment by OckhamOdyssey** [comment]
> Why change the domain extension ?

The original domain expired and someone else buy it to squat it.
