### ISSUE TITLE
Website should support mobile

### ISSUE THREAD

**Issue by AlexanderMisel** [marktext/website#9]
The layout of the website is fine on PC browser, but it will be a mess when using a mobile browser.

**Comment by Jocs** [comment]
PR is welcome.

**Comment by okawa-h** [comment]
Can I make it responsive? Do you have mobile design?
Is it OK to leave it to me?

**Comment by Jocs** [comment]
@okawa-h Sorry, we have no mobile design, great thanks, if you want to fix this issue.

**Comment by okawa-h** [comment]
I will be responsive, wait for PR.

**Comment by okawa-h** [comment]
@Jocs create PR.
